; ExpressLRS PlatformIO Project Configuration File

[platformio]
extra_configs =
	# keep common first
	targets/common.ini
	targets/unified.ini

# ---- SimpliFly custom targets ----

[env:SimpliFly_2G4_RX_via_UART]
extends = env:Unified_ESP32S3_2400_RX_via_UART
board_config = simplifly.rx_2400.simplifly_2g4_rx

[env:SimpliFly_2G4_RX_via_WIFI]
extends = env:Unified_ESP32S3_2400_RX_via_WIFI
board_config = simplifly.rx_2400.simplifly_2g4_rx

[env:SimpliFly_2G4_TX_via_UART]
extends = env:Unified_ESP32S3_2400_TX_via_UART
board_config = simplifly.tx_2400.simplifly_2g4_tx

[env:SimpliFly_2G4_TX_via_WIFI]
extends = env:Unified_ESP32S3_2400_TX_via_WIFI
board_config = simplifly.tx_2400.simplifly_2g4_tx

[env:SimpliFly_Dual_ELRS_RX_via_UART]
extends = env:Unified_ESP32S3_LR1121_RX_via_UART
board_config = simplifly.rx_dual.simplifly_dual_rx

[env:SimpliFly_Dual_ELRS_RX_via_WIFI]
extends = env:Unified_ESP32S3_LR1121_RX_via_WIFI
board_config = simplifly.rx_dual.simplifly_dual_rx

[env:SimpliFly_Dual_ELRS_TX_via_UART]
extends = env:Unified_ESP32S3_LR1121_TX_via_UART
board_config = simplifly.tx_dual.simplifly_dual_tx

[env:SimpliFly_Dual_ELRS_TX_via_WIFI]
extends = env:Unified_ESP32S3_LR1121_TX_via_WIFI
board_config = simplifly.tx_dual.simplifly_dual_tx

# ------------------------- TARGET ENV DEFINITIONS -----------------

[env:native]
platform = native
framework =
test_ignore = test_embedded
lib_ignore = BUTTON, DAC, LQCALC, LBT, SPIEx, PWM, WIFI, TCPSOCKET, LR1121Driver, SX127xDriver
build_src_filter = ${common_env_data.build_src_filter} -<ESP32*.*> -<ESP8*.*> -<tx_*.cpp> -<rx_*.cpp> -<common.*> -<config.*>
build_flags =
	-std=c++11
	-Iinclude
	-D PROGMEM=""
	-D UNIT_TEST=1
	-D TARGET_NATIVE
